version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: finvault-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: finvault-user-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/user_service
      - JWT_SECRET=your_default_jwt_secret_key_must_be_at_least_32_bytes_long
      - INTERNAL_KEY=default_internal_secret_key_123456
    depends_on:
      - postgres

  merchant-service:
    build:
      context: ./services/merchant-service
      dockerfile: Dockerfile
    container_name: finvault-merchant-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/merchant_service
      - JWT_SECRET=your_default_jwt_secret_key_must_be_at_least_32_bytes_long
      - INTERNAL_KEY=default_internal_secret_key_123456
    depends_on:
      - postgres

  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    container_name: finvault-notification-service
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/notification_service
    depends_on:
      - postgres

  wallet-service:
    build:
      context: ./services/wallet-service
      dockerfile: Dockerfile
    container_name: finvault-wallet-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/wallet_service
      - INTERNAL_KEY=default_internal_secret_key_123456
    depends_on:
      - postgres

  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    container_name: finvault-payment-service
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/payment_service
      - INTERNAL_KEY=default_internal_secret_key_123456
      - WALLET_SERVICE_URL=http://wallet-service:3004
    depends_on:
      - postgres

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: finvault-auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/auth_service
      - ACCESS_TOKEN_SECRET=d7aec1b51b32d434b4c2e29f6b7e12ad0ea34f68ad9203c91f244d95f87adeb7dc6bc157976ffeedc6b1b5a109fc01d7c419d69bcf59d873e65e4409f88f9f64
      - USER_SERVICE_URL=http://user-service:3002
      - WALLET_SERVICE_URL=http://wallet-service:3004
      - INTERNAL_API_KEY=default_internal_secret_key_123456
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - postgres

  admin-service:
    build:
      context: ./services/admin-service
      dockerfile: Dockerfile
    container_name: finvault-admin-service
    ports:
      - "3007:3007"
    environment:
      - PORT=3007
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/admin_service
      - INTERNAL_KEY=default_internal_secret_key_123456
      - USER_SERVICE_URL=http://user-service:3002
      - MERCHANT_SERVICE_URL=http://merchant-service:3003
      - WALLET_SERVICE_URL=http://wallet-service:3004
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - postgres

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: finvault-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ACCESS_TOKEN_SECRET=d7aec1b51b32d434b4c2e29f6b7e12ad0ea34f68ad9203c91f244d95f87adeb7dc6bc157976ffeedc6b1b5a109fc01d7c419d69bcf59d873e65e4409f88f9f64
      - CLIENT_URL=http://localhost:5173
      - USER_SERVICE_URL=http://user-service:3002
      - MERCHANT_SERVICE_URL=http://merchant-service:3003
      - AUTH_SERVICE_URL=http://auth-service:3001
      - WALLET_SERVICE_URL=http://wallet-service:3004
      - PAYMENT_SERVICE_URL=http://payment-service:3005
      - NOTIFICATION_SERVICE_URL=http://notification-service:3006
      - ADMIN_SERVICE_URL=http://admin-service:3007
    depends_on:
      - auth-service
      - admin-service
      - user-service
      - merchant-service
      - notification-service
      - wallet-service
      - payment-service

volumes:
  postgres_data: